version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_ram_accept"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/no_create"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/tests"
    update_schedule: "daily"

  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
